### ISSUE TITLE
Plugin support for jenkins 2.320 or higher

### ISSUE THREAD

**Issue by ibrahimuysal** [jenkinsci/mac-plugin#25]
### What feature do you want to see added?

Current version of this plugin is not support jenkins version 2.320 or higher due to guava updates in jenkins core.
https://www.jenkins.io/changelog-old/#v2.320

[### Upstream changes

_No response_](https://www.jenkins.io/blog/2021/11/09/guava-upgrade/
Deprecated: com.google.common.base.Objects.ToStringHelper)https://www.jenkins.io/blog/2021/11/09/guava-upgrade/
Deprecated: [com.google.common.base.Objects.ToStringHelper](https://guava.dev/releases/20.0/api/docs/com/google/common/base/Objects.ToStringHelper.html)

**Comment by mat1e** [comment]
Released in v1.5.1
